# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

# Text to speech
tts:
  - platform: google_translate

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml
input_boolean: !include input_booleans.yaml

http:
  use_x_forwarded_for: true
  trusted_proxies:
    - 172.30.33.0/24
    - 172.30.33.1
    - 173.245.48.0
    - 103.31.4.0
    - 103.22.200.0
    - 103.21.244.0
    - 141.101.64.0
    - 108.162.192.0
    - 190.93.240.0
    - 188.114.96.0
    - 197.234.240.0
    - 198.41.128.0
    - 162.158.0.0
    - 104.16.0.0
    - 104.24.0.0
    - 172.64.0.0
    - 131.0.72.0
    - 172.30.33.8
    - 198.41.192.47
    - 172.30.33.11
    - 172.30.33.10
    - 172.30.33.7

lovelace:
  mode: yaml

homeassistant:
  packages: !include_dir_named packages
  external_url: !secret external_url
  internal_url: !secret internal_url
  currency: PLN
  country: PL
  allowlist_external_dirs:
  - "/config"

recorder:
  db_url: !secret mariaDb_connection_string
  purge_keep_days: 7

influxdb:
  host: !secret influxDb_host
  port: !secret influxDb_port
  database: homeassistant_influx
  username: !secret influxDb_username
  password: !secret influxDb_password
  max_retries: 3
  default_measurement: state
  include:
    entities:
      - group.family
      - input_boolean.alarm_armed
      - input_boolean.alarm_silent
      - binary_sensor.all_devices
      - light.all_lights
      - climate.amelia_s_thermostat
      - sensor.0x00158d00044bc01c_temperature
      - input_boolean.away_mode
      - sensor.bedroom_temperature
      - cover.shelly_shsw_25_4c752533ee84
      - sensor.0x00158d00044c015e_temperature
      - sensor.disk_free
      - sensor.disk_use_percent
      - sensor.disk_use
      - person.dominika
      - weather.dom
      - input_boolean.home_occupancy
      - binary_sensor.kitchen_window_contact
      - sensor.mariadb_size
      - binary_sensor.bedroom_window_contact
      - person.robert
      - sun.sun
      - sensor.weather_temperature
      - sensor.living_room_temperature
      - sensor.bathroom_temperature
      - binary_sensor.thermomix
      - sensor.thermostat_in_living_room_position
      - binary_sensor.tv
      - input_boolean.tv


logger:
  logs:
    custom_components.extended_openai_conversation: info

google_assistant: !include google_assistant.yaml

frontend:
  extra_module_url:
    - /hacsfiles/lovelace-card-mod/card-mod.js
    - /hacsfiles/Bubble-Card/bubble-pop-up.js
  themes: !include_dir_merge_named themes

# variable: !include variables.yaml

light:
  - platform: group
    name: Kitchen lights
    entities:
      - light.kitchen_lights_light_l1
      - light.kitchen_lights_light_l2
      - light.shelly_shsw_1_c45bbe76cec1
  - platform: template
    lights:
      bedroom_light:
        friendly_name: "Bedroom light"
        turn_on:
        turn_off:
        set_level:
      bathroom_light:
        friendly_name: "Bathroom light"
        turn_on:
        turn_off:
        set_level:

alert: !include alerts.yaml

timer:
  away_mode_setting_timer:
    name: Start za
    duration: "00:05:00"
  away_mode_timeout_timer:
    name: Koniec za
  kitchen_window_timer:
    name: Kitchen window timer
    duration: "00:01:00"

input_datetime:
  away_mode_timeout:
    name: Away mode timeout
    has_date: true
    has_time: true
  away_mode_counter:
    name: Away mode counter
    has_time: true

spotcast:
  sp_dc: !secret spotcast_sp_dc
  sp_key: !secret spotcast_sp_key

# Enigma2
# enigma:
#   devices:
#     - host: 192.168.0.112
#       port: 80
#       name: Dreambox
#       timeout: 20
#       username: root
#       picon: picon

notify: !include notify.yaml

stt:
  - platform: google_cloud_stt
    key_file: googlecloud.json
    model: command_and_search

yeelight:
  devices:
    192.168.0.100:
      name: Tv lights


rest_command: !include rest_command.yaml

vacuum:
  - platform: miio2
    host: 192.168.0.106
    token: !secret lucy_token
    name: Lucy

camera:
  - platform: xiaomi_cloud_map_extractor
    host: 192.168.0.106
    token: !secret lucy_token
    username: !secret xiaomi_username
    password: !secret xiaomi_password
    draw: ["all"]
    attributes:
      - calibration_points
      - vacuum_position
      - vacuum_room
      - vacuum_room_name
    scan_interval:
      seconds: 3
    map_transformation:
      scale: 1.5
      trim:
        top: 35
        bottom: 42
        left: 42
        right: 32

binary_sensor:
  - platform: template
    sensors:
      #Blitzwolf smartplug
      tv:
        friendly_name: "Tv"
        icon_template: mdi:television-box
        delay_off:
          seconds: 30
        value_template: "{{states('sensor.0x588e81fffed97f99_power') | float > 5 }}"
      #Tv source = TV
      tv_source_tv:
        friendly_name: "Tv Source Tv"
        icon_template: mdi:television-box
        delay_off:
          minutes: 3
        value_template: "{{states('sensor.0x588e81fffed97f99_power') | float >= 44 }}"
      #Tv source = Minix
      tv_source_minix:
        friendly_name: "Tv Source Minix"
        icon_template: mdi:television-box
        delay_off:
          minutes: 3
        value_template: "{{states('sensor.0x588e81fffed97f99_power') | float < 44 and states('sensor.0x588e81fffed97f99_power') | float > 10 }}"
      amelia_room_occupancy:
        friendly_name: "Amelia room occupancy"
        icon_template: mdi:walk
        value_template: "{{states('binary_sensor.0x00158d0005729974_occupancy') == 'on' or states('binary_sensor.amelia_motion_sensor_2_occupancy') == 'on' }}"
      home_occupancy:
        friendly_name: "{{states.input_text.home_occupancy_last_trigger.state}}"
        icon_template: mdi:walk
        value_template: "{{ states.input_boolean.home_occupancy.state == 'on' }}"
        device_class: occupancy
      living_room_occupancy:
        friendly_name: "Living room presence"
        icon_template: mdi:account-group
        value_template: "{{states('binary_sensor.0x00158d00057280cd_occupancy') == 'on' or states('binary_sensor.presence') == 'on' }}"
        device_class: presence
      thermomix:
        friendly_name: "Thermomix"
        icon_template: mdi:pot-steam
        value_template: "{{ states('device_tracker.thermomix') == 'home' }}"
      all_devices:
        friendly_name: "All devices"
        icon_template: mdi:cellphone-link
        value_template: "{{states('light.all_lights') == 'on' or states('input_boolean.tv') == 'on' or states('media_player.all_media_players') == 'on' or states('media_player.all_media_players') == 'playing'}}"

sensor:
  - platform: sql
    db_url: !secret mariaDb_connection_string
    queries:
      - name: "MariaDb size"
        query: 'SELECT table_schema "database", Round(Sum(data_length + index_length) / 1024 / 1024, 1) "value" FROM information_schema.tables WHERE table_schema="homeassistant" GROUP BY table_schema;'
        column: "value"
        unit_of_measurement: MB
  # - platform: systemmonitor
  #   resources:
  #     - type: disk_use_percent
  #     - type: disk_use
  #     - type: disk_free
  #     - type: memory_use_percent
  #     - type: memory_use
  #     - type: memory_free
  #     - type: processor_use
  #     - type: processor_temperature
  - platform: template
    sensors:
      weather_temperature:
        friendly_name: "Temperatura"
        unit_of_measurement: "°C"
        value_template: "{{ state_attr('weather.dom', 'temperature') }}"
      bathroom_temperature:
        friendly_name: "Temperatura w łazience"
        unit_of_measurement: "°C"
        value_template: "{{ state_attr('climate.thermostat_in_bathroom', 'current_temperature') }}"
      # living_room_temperature:
      #   friendly_name: "Temperatura w salonie"
      #   unit_of_measurement: "°C"
      #   value_template: "{{ state_attr('climate.0x842e14fffee19a4b_climate', 'current_temperature') }}"
      bathroom_thermostat_mode:
        friendly_name: "Tryb termostatu w łazience"
        value_template: "{{ state_attr('climate.thermostat_in_bathroom', 'system_mode') }}"
      amelia_thermostat_mode:
        friendly_name: "Tryb termostatu u Amelii"
        value_template: "{{ state_attr('climate.thermostat_in_amelias_room', 'system_mode') }}"
      sun_azimuth:
        friendly_name: "Azymut słońca"
        unit_of_measurement: "degrees"
        value_template: "{{ state_attr('sun.sun', 'azimuth') }}"
      sun_elevation:
        friendly_name: "Wysokość słońca"
        unit_of_measurement: "degrees"
        value_template: "{{ state_attr('sun.sun', 'elevation') }}"
      weather_cloud_coverage:
        friendly_name: "Zachmurzenie"
        unit_of_measurement: "%"
        value_template: "{{ state_attr('weather.dom', 'cloud_coverage') }}"
  - platform: history_stats
    name: Living room thermostat today
    entity_id: binary_sensor.thermostat_in_living_room_heating
    state: 'on'
    type: time
    start: '{{ now().replace(hour=0).replace(minute=0).replace(second=0) }}'
    end: '{{ now() }}'
  - platform: history_stats
    name: Lucy this week
    entity_id: vacuum.lucy
    state: 'cleaning'
    type: time
    start: '{{ as_timestamp( now().replace(hour=0, minute=0, second=0, microsecond=0) ) - now().weekday() * 86400 }}'
    end: '{{ now() }}'
  - platform: rest
    name: Eleven Labs Character Count
    resource: https://api.elevenlabs.io/v1/user/subscription
    headers:
      xi-api-key: !secret eleven_labs_token
    value_template: "{{ value_json.character_count }}"
    json_attributes:
      - character_limit
    scan_interval: 3600

powercalc:
  !include powercalc.yaml
  # - platform: folder
  #   folder: http://192.168.0.120:8000/fs/mnt/UsbDrive/AUDIO/

shell_command:
  trim_storage: "systemctl start fstrim.service"
  fstrim: "fstrim -v /config > /config/fstrimlog.txt"
  mount_usb_drive: "mkdir -p /media/AUDIO;mount -t cifs -o vers=3.0,noserverino,username=root //192.168.0.120/UsbDrive/AUDIO /media/AUDIO"

assist_pipeline:
  debug_recording_dir: /config/shared/assist_pipeline