resources:
  - url: /local/mini-media-player-bundle.js?v=1.9.1
    type: module
  - url: /local/vacuum-card.js
    type: module
  - url: /local/battery-state-card.js
    type: module
  - url: /hacsfiles/scheduler-card/scheduler-card.js
    type: module
  - url: /hacsfiles/vertical-stack-in-card/vertical-stack-in-card.js
    type: js
  - url: /hacsfiles/lovelace-xiaomi-vacuum-map-card/xiaomi-vacuum-map-card.js
    type: module
  - url: /hacsfiles/lovelace-time-picker-card/time-picker-card.js
    type: module
  - url: /hacsfiles/lovelace-card-mod/card-mod.js
    type: module
  - url: /hacsfiles/flipdown-timer-card/flipdown-timer-card.js
    type: module
  - url: /hacsfiles/timer-bar-card/timer-bar-card.js
    type: module

title: Dom
views:
  - path: default_view
    title: Dom
    badges:
      - entity: sun.sun
      - entity: sensor.weather_temperature
        name: "Na zewnątrz"
      - entity: sensor.living_room_temperature
        name: "Salon"
      - entity: sensor.0x00158d00044c015e_temperature
        name: "Sypialnia"
      - entity: sensor.0x00158d00044bc01c_temperature
        name: "Amelia"
      - entity: sensor.bathroom_temperature
        name: "Łazienka"
      - entity: sensor.kitchen_window_temperature
        name: "Kuchnia"
      - entity: input_boolean.nap_time
        name: "Drzemka"
        icon: mdi:sleep
    cards:
      - type: entities
        title: "Światło"
        entities:
          - type: section
            label: Salon
          - entity: light.tv_lights
            name: Lampka TV
          - entity: switch.living_room_lights_l1
            name: Stół
          - entity: switch.living_room_lights_l2
            name: Front
          - entity: switch.living_room_lights_l3
            name: Sofa
          - type: section
            label: Pokój Amelii
          - entity: light.0xbc33acfffe6d82d0_light
            name: Amelia sufit
          - type: section
            label: Kuchnia
          - entity: light.kitchen_lights
            name: Kuchnia
          - entity: light.kitchen_lights_light_l1
            name: Kuchnia
          - entity: light.kitchen_lights_light_l2
            name: Kuchnia blat
          - entity: light.shelly_shsw_1_c45bbe76cec1
            name: Listwa
          - type: section
            label: Balkon
          - entity: switch.711315732cf432d1f59f
            name: Balkon
      - type: entities
        entities:
          - entity: input_boolean.tv
            name: TV
            icon: mdi:television
      - type: weather-forecast
        entity: weather.dom
      - type: custom:mini-media-player
        entity: media_player.dreambox
        icon: mdi:television-classic
        artwork: cover
      - type: custom:mini-media-player
        entity: media_player.chromecast
        icon: mdi:cast
        artwork: cover
      - type: thermostat
        entity: climate.0x842e14fffee19a4b_climate
        name: Termostat w salonie
      - type: thermostat
        entity: climate.thermostat_in_bathroom
        name: Termostat w łazience
      - type: thermostat
        entity: climate.thermostat_in_amelias_room
        name: Termostat u Amelki
      - type: custom:mini-media-player
        entity: media_player.kitchens_speaker
        artwork: cover
        icon: mdi:google-home
        source: icon
        shortcuts:
          columns: 2 # Max buttons per row
          rows: 3
          buttons:
            # Start predefined playlist
            - icon: mdi:baby-face
              type: service
              id: spotcast.start
              data:
                entity_id: media_player.kitchens_speaker
                uri: spotify:playlist:1LUeWgLXGPvDU9eqcLDRVP
                random_song: true
            - icon: mdi:sleep
              media_content_type: playlist
              media_content_id: "spotify:playlist:1LUeWgLXGPvDU9eqcLDRVP"
            - id: "http://31.192.216.10/rmf_fm"
              name: RMF FM
              app_name: RMF FM
              type: music
              icon: "https://cdn-profiles.tunein.com/s1217/images/logoq.png?t=636353"
              entity_picture: "https://cdn-profiles.tunein.com/s1217/images/logoq.png?t=636353"
              entity_picture_local: "api/media_player_proxy/media_player.mini?token=38e210bffde0580fbe03323d52f293d463604cf553a96ba760f60d7e78966ec1&cache=2b8bd5b0bbf7376e"
            - id: "https://zt.cdn.eurozet.pl/zet-tun.mp3"
              name: RadioZET
              type: music
      - type: entities
        entities:
          - type: custom:mini-media-player
            entity: media_player.photo_frame
            show_source: true
            group: true
            artwork: cover
            icon: mdi:google-home
            source: icon
            shortcuts:
              columns: 2 # Max buttons per row
              rows: 3
              buttons:
                # Start predefined playlist
                - icon: mdi:baby-face
                  type: service
                  id: spotcast.start
                  data:
                    entity_id: media_player.photo_frame
                    uri: spotify:playlist:1LUeWgLXGPvDU9eqcLDRVP
                    random_song: true
                - icon: mdi:youtube
                  type: service
                  service: media_extractor.play_media
                  data:
                    entity_id: media_player.photo_frame
                    media_content_id: https://youtu.be/uHToZTZimcs
                    media_content_type: video/youtube
                - id: "http://31.192.216.10/rmf_fm"
                  name: RMF FM
                  app_name: RMF FM
                  type: music
                  icon: "https://cdn-profiles.tunein.com/s1217/images/logoq.png?t=636353"
                  entity_picture: "https://cdn-profiles.tunein.com/s1217/images/logoq.png?t=636353"
                  entity_picture_local: "api/media_player_proxy/media_player.mini?token=38e210bffde0580fbe03323d52f293d463604cf553a96ba760f60d7e78966ec1&cache=2b8bd5b0bbf7376e"
                - id: "https://zt.cdn.eurozet.pl/zet-tun.mp3"
                  name: RadioZET
                  type: music
      - type: custom:mini-media-player
        entity: media_player.amelias_speaker
        artwork: cover
        icon: mdi:google-home
        source: icon
        shortcuts:
          columns: 2 # Max buttons per row
          rows: 3
          buttons:
            # Start predefined playlist
            - icon: mdi:baby-face
              type: service
              id: spotcast.start
              data:
                entity_id: media_player.amelias_speaker
                uri: spotify:playlist:1LUeWgLXGPvDU9eqcLDRVP
                random_song: true
            - icon: mdi:sleep
              media_content_type: playlist
              media_content_id: "spotify:playlist:1LUeWgLXGPvDU9eqcLDRVP"
            - id: "http://31.192.216.10/rmf_fm"
              name: RMF FM
              app_name: RMF FM
              type: music
              icon: "https://cdn-profiles.tunein.com/s1217/images/logoq.png?t=636353"
              entity_picture: "https://cdn-profiles.tunein.com/s1217/images/logoq.png?t=636353"
              entity_picture_local: "api/media_player_proxy/media_player.mini?token=38e210bffde0580fbe03323d52f293d463604cf553a96ba760f60d7e78966ec1&cache=2b8bd5b0bbf7376e"
            - id: "https://zt.cdn.eurozet.pl/zet-tun.mp3"
              name: RadioZET
              type: music
      - type: "custom:vacuum-card"
        entity: vacuum.lucy
        stats:
          default:
            - attribute: filter_left
              unit: hours
              subtitle: Filter
            - attribute: side_brush_left
              unit: hours
              subtitle: Side brush
            - attribute: main_brush_left
              unit: hours
              subtitle: Main brush
            - attribute: sensor_dirty_left
              unit: hours
              subtitle: Sensors
          cleaning:
            - attribute: cleaned_area
              unit: m2
              subtitle: Cleaning area
            - attribute: cleaning_time
              unit: minutes
              subtitle: Cleaning time
        actions:
          - name: Clean living room
            service: script.living_room_cleaning
            icon: "mdi:sofa"
          - name: Clean bedroom
            service: script.bedroom_cleaning
            icon: "mdi:bed-empty"
          - name: Clean kitchen
            service: script.kitchen_cleaning
            icon: "mdi:silverware-fork-knife"
          - name: Clean toilet
            service: script.toilet_cleaning
            icon: "mdi:paper-roll"
          - name: Clean bathroom
            service: script.bathroom_cleaning
            icon: "mdi:shower"
          - name: Clean Amelia's room
            service: script.amelias_cleaning
            icon: "mdi:unicorn"
          
  - path: living_room
    title: Salon
    badges:
    cards:
      - type: entities
        entities:
          - entity: input_boolean.sleeping_mode
            name: Tryb nocny
            icon: mdi:sleep
      - type: custom:scheduler-card
        discover_existing: false
        display_options:
          primary_info:
            - "{name}: {action}"
          secondary_info: relative-time
          icon: "hass:action"
        customize:
          climate.0x842e14fffee19a4b_climate:
            name: "Termostat"
            icon: thermometer
            actions:
              - service: climate.set_temperature
                variables:
                  temperature:
                    name: "Temperatura"
                    min: 5
                    max: 30
                    step: 1
                icon: thermometer
                name: "Ustaw temperature"
        groups:
          - thermostats:
              domains: [climate]
              icon: home-thermometer-outline
              actions:
                - icon: thermometer-chevron-up
                  service: set_temperature
            name: Termostat
            include: 
              - climate.0x842e14fffee19a4b_climate
      - type: thermostat
        entity: climate.0x842e14fffee19a4b_climate
        name: Termostat
      - type: entities
        title: "Światło"
        entities:
          - entity: light.tv_lights
            name: Lampka TV
          - entity: switch.living_room_lights_l1
            name: Stół
          - entity: switch.living_room_lights_l2
            name: Front
          - entity: switch.living_room_lights_l3
            name: Sofa
      - type: entities
        entities:
          - entity: input_boolean.tv
            name: TV
            icon: mdi:television
      - type: custom:mini-media-player
        entity: media_player.dreambox
        icon: mdi:television-classic
        artwork: cover
      - type: custom:mini-media-player
        entity: media_player.chromecast
        icon: mdi:cast
        artwork: cover
      - type: entities
        entities:
          - type: custom:mini-media-player
            entity: media_player.photo_frame
            show_source: true
            group: true
            artwork: cover
            icon: mdi:google-home
            source: icon
            shortcuts:
              columns: 2 # Max buttons per row
              rows: 3
              buttons:
                # Start predefined playlist
                - icon: mdi:baby-face
                  type: service
                  id: spotcast.start
                  data:
                    entity_id: media_player.photo_frame
                    uri: spotify:playlist:1LUeWgLXGPvDU9eqcLDRVP
                    random_song: true
                - icon: mdi:youtube
                  type: service
                  service: media_extractor.play_media
                  data:
                    entity_id: media_player.photo_frame
                    media_content_id: https://youtu.be/uHToZTZimcs
                    media_content_type: video/youtube
                - id: "http://31.192.216.10/rmf_fm"
                  name: RMF FM
                  app_name: RMF FM
                  type: music
                  icon: "https://cdn-profiles.tunein.com/s1217/images/logoq.png?t=636353"
                  entity_picture: "https://cdn-profiles.tunein.com/s1217/images/logoq.png?t=636353"
                  entity_picture_local: "api/media_player_proxy/media_player.mini?token=38e210bffde0580fbe03323d52f293d463604cf553a96ba760f60d7e78966ec1&cache=2b8bd5b0bbf7376e"
                - id: "https://zt.cdn.eurozet.pl/zet-tun.mp3"
                  name: RadioZET
                  type: music
  - path: bathroom
    title: Łazienka
    cards:
      - type: custom:scheduler-card
        discover_existing: false
        display_options:
          primary_info:
            - "{name}: {action}"
          secondary_info: relative-time
          icon: "hass:action"
        customize:
          climate.thermostat_in_bathroom:
            name: "Termostat"
            icon: thermometer
            actions:
              - service: climate.set_temperature
                variables:
                  temperature:
                    name: "Temperatura"
                    min: 5
                    max: 30
                    step: 1
                icon: thermometer
                name: "Ustaw temperature"
        groups:
          - thermostats:
              domains: [climate]
              icon: home-thermometer-outline
              actions:
                - icon: thermometer-chevron-up
                  service: set_temperature
            name: Termostat
            include: 
              - climate.thermostat_in_bathroom
      - type: thermostat
        entity: climate.thermostat_in_bathroom
        name: Termostat
  - path: amelia
    title: Amelia
    badges:
      - entity: sensor.0x00158d00044bc01c_temperature
        name: "Amelia"
      - entity: sensor.0x00158d00044bc01c_humidity
        name: "Wilgotność"
      - entity: sensor.0x00158d00044bc01c_pressure
        name: "Ciśnienie"
    cards:
      - type: entities
        entities:
          - entity: input_boolean.night_mode
            name: Tryb nocny
            icon: mdi:sleep
      - type: entities
        entities:
          - entity: light.0xbc33acfffe6d82d0_light
            name: Sufit
      - type: custom:mini-media-player
        entity: media_player.amelias_speaker
        artwork: cover
        icon: mdi:google-home
        source: icon
        shortcuts:
          columns: 2 # Max buttons per row
          rows: 3
          buttons:
            # Start predefined playlist
            - icon: mdi:baby-face
              type: service
              id: spotcast.start
              data:
                entity_id: media_player.amelias_speaker
                uri: spotify:playlist:1LUeWgLXGPvDU9eqcLDRVP
                random_song: true
            - icon: mdi:sleep
              media_content_type: playlist
              media_content_id: "spotify:playlist:1LUeWgLXGPvDU9eqcLDRVP"
            - id: "http://31.192.216.10/rmf_fm"
              name: RMF FM
              app_name: RMF FM
              type: music
              icon: "https://cdn-profiles.tunein.com/s1217/images/logoq.png?t=636353"
              entity_picture: "https://cdn-profiles.tunein.com/s1217/images/logoq.png?t=636353"
              entity_picture_local: "api/media_player_proxy/media_player.mini?token=38e210bffde0580fbe03323d52f293d463604cf553a96ba760f60d7e78966ec1&cache=2b8bd5b0bbf7376e"
            - id: "https://zt.cdn.eurozet.pl/zet-tun.mp3"
              name: RadioZET
              type: music
      - type: custom:scheduler-card
        discover_existing: false
        display_options:
          primary_info:
            - "{name}: {action}"
          secondary_info: relative-time
          icon: "hass:action"
        customize:
          climate.thermostat_in_amelias_room:
            name: "Termostat"
            icon: thermometer
            actions:
              - service: climate.set_temperature
                variables:
                  temperature:
                    name: "Temperatura"
                    min: 5
                    max: 30
                    step: 1
                icon: thermometer
                name: "Ustaw temperature"
        groups:
          - thermostats:
              domains: [climate]
              icon: home-thermometer-outline
              actions:
                - icon: thermometer-chevron-up
                  service: set_temperature
            name: Termostat
            include: 
              - climate.thermostat_in_amelias_room
      - type: thermostat
        entity: climate.thermostat_in_amelias_room
        name: Termostat
  - !include /config/views/bedroom.yaml
  - !include /config/views/hall.yaml
  - !include /config/views/kitchen.yaml
  - !include /config/views/balcony.yaml
  - !include /config/views/maintaining.yaml

group:
  lights:
    name: "Światło"
    entities:
      - entity: light.tv_lights
        name: Lampka TV
      - entity: light.0xbc33acfffe6d82d0_light
        name: Amelia sufit
