resources:
  - url: /hacsfiles/mini-media-player/mini-media-player-bundle.js?v=1.16.2
    type: module
  #   - url: /local/mini-media-player-bundle.js?v=1.9.1
  #     type: module
  - url: /local/vacuum-card.js
    type: module
  - url: /local/battery-state-card.js
    type: module
  - url: /hacsfiles/scheduler-card/scheduler-card.js
    type: module
  - url: /hacsfiles/vertical-stack-in-card/vertical-stack-in-card.js
    type: js
  - url: /hacsfiles/lovelace-xiaomi-vacuum-map-card/xiaomi-vacuum-map-card.js
    type: module
  - url: /hacsfiles/lovelace-time-picker-card/time-picker-card.js
    type: module
  - url: /hacsfiles/lovelace-card-mod/card-mod.js
    type: module
  - url: /hacsfiles/flipdown-timer-card/flipdown-timer-card.js
    type: module
  - url: /hacsfiles/timer-bar-card/timer-bar-card.js
    type: module
  - url: /hacsfiles/button-card/button-card.js
    type: module
  - url: /hacsfiles/lovelace-auto-entities/auto-entities.js
    type: module
  - url: /hacsfiles/my-cards/my-cards.js
    type: module
  - url: /hacsfiles/mini-graph-card/mini-graph-card-bundle.js
    type: module
  - url: /hacsfiles/swipe-card/swipe-card.js
    type: module

title: Dom
views:
  - !include /config/views/home.yaml
  - !include /config/views/living_room.yaml
  - !include /config/views/bathroom.yaml
  - !include /config/views/amelia.yaml
  - !include /config/views/bedroom.yaml
  - !include /config/views/hall.yaml
  - !include /config/views/kitchen.yaml
  - !include /config/views/balcony.yaml
  - !include /config/views/maintaining.yaml

group:
  lights:
    name: "Światło"
    entities:
      - entity: light.tv_lights
        name: Lampka TV
      - entity: light.0xbc33acfffe6d82d0_light
        name: Amelia sufit
